source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ValidatorExample', :exclusive => true do
  pod "swift-text-validator", :path => "../"
end

target 'ValidatorExampleTests', :exclusive => true do
  pod "swift-text-validator", :path => "../"


end

link_with 'ValidatorExample', 'ValidatorExampleTests'
