source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JWValidator_Example', :exclusive => true do
  pod "JWValidator", :path => "../"
end

target 'JWValidator_Tests', :exclusive => true do
  pod "JWValidator", :path => "../"


end

link_with 'JWValidator_Example', 'JWValidator_Tests'