source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Validator_Example', :exclusive => true do
  pod "swift-text-validator", :path => "../"
end

target 'Validator_Tests', :exclusive => true do
  pod "swift-text-validator", :path => "../"


end

link_with 'Validator_Example', 'Validator_Tests'